language: node_js
node_js: 10
cache:
  directories:
    - node_modules
before_install:
  - yarn global add greenkeeper-lockfile@2 now
install:
  - yarn
before_script:
  - greenkeeper-lockfile-update
script:
  - yarn build
after_script:
  - greenkeeper-lockfile-upload
deploy:
  - provider: script
    script: now --token $NOW_TOKEN && now alias --token $NOW_TOKEN
    skip_cleanup: true
    on:
      master: true